#include "assembler.hpp"
#include "interpreter.hpp"

int main() {
    // Example assembly input
    std::string assemblyCode =
        "MOV R1, 10\n"
        "MOV R2, 5\n"
        "ADD R3, R1, R2\n"
        "PRINT R3\n"
        "HALT\n";

    // Convert to bytecode
    std::vector<uint8_t> bytecode = assemble(assemblyCode);

    // Print the generated bytecode
    std::cout << "Generated Bytecode: ";
    for (uint8_t byte : bytecode) {
        printf("0x%02X ", byte);
    }
    std::cout << std::endl;

    // Run the virtual machine
    VirtualMachine vm;
    vm.loadBytecode(bytecode);
    vm.run();

    return 0;
}
